
package org.acme.soap_service.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MySoapService", targetNamespace = "http://acme.org/soap-service/V1", wsdlLocation = "/services/soap-service/V1/MySoapService.wsdl")
public class MySoapService_Service
    extends Service
{

    private final static URL MYSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYSOAPSERVICE_EXCEPTION;
    private final static QName MYSOAPSERVICE_QNAME = new QName("http://acme.org/soap-service/V1", "MySoapService");

    static {
        MYSOAPSERVICE_WSDL_LOCATION = org.acme.soap_service.v1.MySoapService_Service.class.getResource("/services/soap-service/V1/MySoapService.wsdl");
        WebServiceException e = null;
        if (MYSOAPSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/services/soap-service/V1/MySoapService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MYSOAPSERVICE_EXCEPTION = e;
    }

    public MySoapService_Service() {
        super(__getWsdlLocation(), MYSOAPSERVICE_QNAME);
    }

    public MySoapService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns MySoapService
     */
    @WebEndpoint(name = "MySoapServicePort")
    public MySoapService getMySoapServicePort() {
        return super.getPort(new QName("http://acme.org/soap-service/V1", "MySoapServicePort"), MySoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MySoapService
     */
    @WebEndpoint(name = "MySoapServicePort")
    public MySoapService getMySoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://acme.org/soap-service/V1", "MySoapServicePort"), MySoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYSOAPSERVICE_EXCEPTION!= null) {
            throw MYSOAPSERVICE_EXCEPTION;
        }
        return MYSOAPSERVICE_WSDL_LOCATION;
    }

}
