
package org.acme.soap_service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.acme.soap_service.interfaces.v1.CheckServiceHealthRequestType;
import org.acme.soap_service.interfaces.v1.CheckServiceHealthResponseType;
import org.acme.soap_service.interfaces.v1.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MySoapService", targetNamespace = "http://acme.org/soap-service/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MySoapService {


    /**
     * 
     * @param request
     * @return
     *     returns org.acme.soap_service.interfaces.v1.CheckServiceHealthResponseType
     */
    @WebMethod
    @WebResult(name = "checkServiceHealthResponse", targetNamespace = "http://acme.org/soap-service/interfaces/V1", partName = "response")
    public CheckServiceHealthResponseType checkServiceHealth(
        @WebParam(name = "checkServiceHealthRequest", targetNamespace = "http://acme.org/soap-service/interfaces/V1", partName = "request")
        CheckServiceHealthRequestType request);

}
